### ISSUE TITLE
Release tracker

### ISSUE THREAD

**Issue by Zverik** [Zverik/qgis_wp#1]
What to do before this plugin is no longer experimental and turns 1.0.

- [x] Atlas creation ([ref](https://github.com/qgis/QGIS/blob/release-2_18/tests/src/python/test_qgsatlascomposition.py))
- [x] Choose, open ([ref](https://github.com/qgis/QGIS/blob/release-2_18/python/plugins/processing/algs/gdal/ogr2ogr.py)) and style a GeoPackage file made with ogr2ogr (see [osm_file_dialog.py](https://github.com/3liz/QuickOSM/blob/master/ui/osm_file_dialog.py) and [osm_parser.py](https://github.com/3liz/QuickOSM/blob/master/quick_osm_processing/parser/osm_parser.py))
- [x] Icon for the plugin and the menu
- [x] Plugin build system (similar to [QMS](https://github.com/nextgis/quickmapservices/)? [Plugin Builder](http://g-sherman.github.io/Qgis-Plugin-Builder/)?) [pb_tool](http://g-sherman.github.io/plugin_build_tool/)
- [x] [Publish plugin](http://plugins.qgis.org/)

At this point publish the blog post in SHTOSM.

- [x] Merge https://github.com/qgis/QGIS/pull/4730
- [x] Find a workaround for the 2.14 atlas map scaling issue
- [x] Decide on downloading data inside a polygon from Overpass API ([ref](https://github.com/3liz/QuickOSM))
- [x] Internationalization
- [x] Step-by-step instructions in Russian and English
